@startuml ユースケース図
left to right direction
'下記の図は、社員の資格取得状況を記録するためのシステムのクラス図の一部です。次のシナリオに基づいて、オブジェクト図を記述しなさい。
'【シナリオ】
'高橋洋平さんは、情報処理技術者試験の情報処理安全確保支援士の試験に合格し、2020年10月21日にそのことを申請しました。樋口正之さんもその試験に合格しています。
'さらに、高橋洋平さんは、LinuC試験Level１も合格し、2021年3月28日に会社に申し出ました。
object "<u>社員1:社員</u>" as S1 {
氏名=高橋洋平
}

object "<u>社員2:社員</u>" as S2 {
氏名=樋口正之
}

object "<u>資格1:資格</u>" as C1 {
名称=情報処理安全確保支援士
}

object "<u>資格2:資格</u>" as C2 {
名称=LinuC試験Level1
}

S1 -- C1
S1 -- C2
S2 -- C1