@startuml 診療予約システム_ステートマシン図
' left to right direction
[*] -right-> メニュー: 接続
メニュー -down-> 予約と確認: 予約と確認を選択する
予約と確認 -up-> メニュー: 取り消しボタンを押す
予約と確認 -right-> あなたの順番: 登録ボタンを押す
あなたの順番 -left-> 予約と確認: 確認ボタンを押す
あなたの順番 -up-> メニュー: メニューへボタンを押す
今の順番 -up-> メニュー: メニューへボタンを押す
メニュー -down-> 今の順番: 今の順番ボタンを押す
メニュー -right-> [*] : 切断
@enduml