@startuml ユースケース図
'【シナリオ】
'11月21日、重要顧客の高橋洋平さんが売り場に来られて、テレビ（型式V12345）を２台と冷蔵庫（型式R8765）１台注文していきました。
'12月23日高田利恵さんも同じ冷蔵庫を1台注文していきました。
'12月30日に大坪直之さんが来店し、売り場のプロジェクタ（型式P1122）を熱心に見ていましたが、残念ながら注文せずにお帰りになりました。
left to right direction
object "<u>顧客2: 顧客</u>" as c {
氏名=髙田利恵
住所=盛岡
}

object "<u>商品1: 商品</u>" as s1 {
商品名=テレビ
型式=V12345
}

object "<u>商品2: 商品</u>" as s2 {
商品名=冷蔵庫
型式=R8765
}

object "<u>重要顧客1:重要顧客</u>" as D {
氏名=高橋洋平
住所=盛岡
}

object "<u>注文1:注文リスト</u>" as T1 {
注文日=11月21日
数量=2
}

object "<u>注文2:注文リスト</u>" as T2 {
注文日=11月21日
数量=1
}

object "<u>注文3:注文リスト</u>" as T3 {
注文日=12月23日
数量=1
}

D -- T1
D -- T2
T1 -- s1
T2 -- s2
T3 -- s1
c -- T3
@enduml